/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvanceComponent: typeof import('./src/components/AdvanceComponent.vue')['default']
    BasicComponent: typeof import('./src/components/BasicComponent.vue')['default']
    GlobalComponent: typeof import('./src/components/GlobalComponent.vue')['default']
    NotifierComponent: typeof import('./src/plugins/vuetify-notifier/components/NotifierComponent.vue')['default']
    NotifierDialog: typeof import('./src/plugins/vuetify-notifier/components/NotifierDialog.vue')['default']
    NotifierMenu: typeof import('./src/plugins/vuetify-notifier/components/NotifierMenu.vue')['default']
    NotifierToast: typeof import('./src/plugins/vuetify-notifier/components/NotifierToast.vue')['default']
  }
}
