/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvanceComponent: typeof import('./src/components/AdvanceComponent.vue')['default']
    BasicComponent: typeof import('./src/components/BasicComponent.vue')['default']
    GlobalComponent: typeof import('./src/components/GlobalComponent.vue')['default']
  }
}
